### ISSUE TITLE
测试报错

### ISSUE THREAD

**Issue by wang2793312458** [JemyCheung/easystreaming#1]
E/StreamingByCameraActivity: streamingState = UNAUTHORIZED_STREAMING_URLextra = -3
E/PLDroidMediaStreaming: Pili-Streaming:Muxer:Init streaming core failed.

E/libc: Access denied finding property "net.dns1"
E/libc: Access denied finding property "net.dns2"
E/libc: Access denied finding property "net.dns3"
E/libc: Access denied finding property "net.dns4"

**Comment by JemyCheung** [comment]
您好，这是由于您的推流地址未授权
1.您可以联系商务，给您的推流域名开通权限
2.您可以在七牛创建直播空间，用七牛的地址推 @wang2793312458

**Comment by wang2793312458** [comment]
我们开通的阿里云直播，但是阿里文档说已经与七牛合作，原来的阿里推流地址不能在七牛上使用吗

**Comment by JemyCheung** [comment]
需要开通白名单，联系商务开通权限 @wang2793312458
