### ISSUE TITLE
PLVideoTextureView怎么更换播放地址

### ISSUE THREAD

**Issue by wang2793312458** [JemyCheung/easystreaming#2]
mPLVideoTextureView.setVideoPath(“新地址”);
        mPLVideoTextureView.start();
这样不好使，请问怎么调用

**Comment by JemyCheung** [comment]
您好，您可以提七牛工单咨询一下哦。
据我所知，播放器sdk是暂时不建议接入的。
这里应该是需要stopPlayback，然后重新初始化播放器，再start @wang2793312458

**Comment by wang2793312458** [comment]
谢谢，我试试
